(()=>{const A='media/anatomy/';const M='media/motion/';const EX={
'machine-chest-press':{name:'Machine Chest Press',cat:'UPPER A · CHEST + TRICEPS',img:A+'machine-chest-press.webp',video:M+'machine-chest-press.mp4',sets:4,reps:'6–8',rest:'75s',cue:'Press smoothly; keep shoulder blades supported.'},
'face-pull':{name:'Face Pull',cat:'UPPER A · REAR DELTS + UPPER BACK',img:A+'face-pull.webp',video:M+'face-pull.mp4',sets:3,reps:'10–12',rest:'45s',cue:'Pull toward eye level and rotate externally.'},
'barbell-hip-thrust':{name:'Barbell Hip Thrust',cat:'LOWER A · GLUTES',img:A+'barbell-hip-thrust.webp',video:M+'barbell-hip-thrust.mp4',sets:4,reps:'8–10',rest:'75s',cue:'Drive through the heels and finish with the pelvis neutral.'},
'lat-pulldown':{name:'Lat Pulldown',cat:'UPPER A · BACK + BICEPS',img:A+'lat-pulldown.webp',video:null,sets:4,reps:'5–7',rest:'60s',cue:'Drive elbows toward your back pockets.'},
'leg-press':{name:'Leg Press',cat:'LOWER A · QUADS + GLUTES',img:A+'leg-press.webp',video:null,sets:4,reps:'8–12',rest:'75s',cue:'Control depth and keep knees tracking over toes.'},
'goblet-squat':{name:'Goblet Squat',cat:'LOWER A · QUADS + GLUTES',img:A+'goblet-squat.webp',video:null,sets:3,reps:'8–10',rest:'60s',cue:'Sit between the hips with a tall torso.'},
'supported-single-arm-dumbbell-row':{name:'Supported DB Row',cat:'UPPER A · BACK',img:A+'supported-single-arm-dumbbell-row.webp',video:null,sets:3,reps:'8–12',rest:'45s',cue:'Keep torso fixed and pull elbow toward hip.'},
'seated-hamstring-curl':{name:'Seated Hamstring Curl',cat:'LOWER A · HAMSTRINGS',img:A+'seated-hamstring-curl.webp',video:null,sets:3,reps:'10–15',rest:'45s',cue:'Curl smoothly without lifting the hips.'},
'standing-calf-raise':{name:'Standing Calf Raise',cat:'LOWER A · CALVES',img:A+'standing-calf-raise.webp',video:null,sets:3,reps:'12–15',rest:'40s',cue:'Pause at the top and control the stretch.'},
'incline-dumbbell-press':{name:'Incline DB Press',cat:'UPPER A · CHEST',img:A+'incline-dumbbell-press.webp',video:null,sets:3,reps:'8–10',rest:'60s',cue:'Keep wrists stacked and shoulder blades anchored.'},
'dumbbell-lateral-raise':{name:'DB Lateral Raise',cat:'UPPER A · SHOULDERS',img:A+'dumbbell-lateral-raise.webp',video:null,sets:3,reps:'10–15',rest:'40s',cue:'Lead with the elbows; stop before shrugging.'},
'backward-sled-drag':{name:'Backward Sled Drag',cat:'KNEE CAPACITY',img:A+'backward-sled-drag.webp',video:null,sets:4,reps:'30–45s',rest:'45s',cue:'Short controlled steps; keep tension through the quads.'}
};
const DEFAULT_PAGES=[['cover','Cover'],['today','Today'],['today-plan','Today Plan'],['next','Next'],['programs','Programs'],['recovery','Recovery / Physio'],['nutrition','Nutrition'],['progress','Progress'],['music','Spotify / Music'],['owner','Owner Controls'],['settings','Settings']].map((x,i)=>({id:x[0],title:x[1],visible:true,drawer:true,bottom:['today','programs','recovery','nutrition','progress'].includes(x[0]),order:i,custom:false,modules:[]}));
const DEF_FEATURES={anatomyMotion:true,formLock:true,autoLoop:true,voiceCue:false,coachingText:true,muscleHighlight:true,timers:true,logging:true,painSafe:true,recoveryMode:true,focusControls:true,editFab:true};
let state=load();let current='today',drawer=false,player=null,tab='animation',editMode=false;
function load(){try{const s=JSON.parse(localStorage.getItem('icv3')||'{}');return {pages:Array.isArray(s.pages)&&s.pages.length?s.pages:DEFAULT_PAGES,features:{...DEF_FEATURES,...s.features},focus:{upper:45,lower:55,recovery:60,mobility:45,cardio:30,core:40,strength:65,...s.focus},motion:s.motion||{},spotify:s.spotify||{},modules:s.modules||{}}}catch(e){return {pages:DEFAULT_PAGES,features:{...DEF_FEATURES},focus:{upper:45,lower:55,recovery:60,mobility:45,cardio:30,core:40,strength:65},motion:{},spotify:{},modules:{}}}}
function save(){localStorage.setItem('icv3',JSON.stringify(state))}
window.__setInsets=(t,b,l,r)=>{const d=document.documentElement.style;d.setProperty('--safe-top',t+'px');d.setProperty('--safe-bottom',b+'px');d.setProperty('--safe-left',l+'px');d.setProperty('--safe-right',r+'px')};
function pageCfg(id){return state.pages.find(p=>p.id===id)}function visiblePages(){return state.pages.filter(p=>p.visible).sort((a,b)=>a.order-b.order)}
function go(id){if(id==='exercise-player')return;const p=pageCfg(id);if(p&&!p.visible){id='today'}current=id;drawer=false;player=null;tab='animation';render();history.pushState({p:id},'', '#'+id)}
function back(){if(drawer){drawer=false;render();return true}if(player){player=null;render();return true}if(current!=='today'){current='today';render();return true}return false}window.appBack=back;
window.addEventListener('popstate',()=>{if(player){player=null;render();return}const id=location.hash.slice(1);if(pageCfg(id))current=id;render()});
function top(title,eyebrow='ILIAS COACH'){return `<div class="topbar"><button class="iconbtn" onclick="appBack()">←</button><div class="title"><div class="eyebrow">${esc(eyebrow)}</div><h1 ${editMode?'class="inlineedit" onclick="renameCurrent()"':''}>${esc(title)}</h1></div><button class="iconbtn" onclick="toggleDrawer()">☰</button></div>`}
function bottom(){const ps=visiblePages().filter(p=>p.bottom).slice(0,5);return `<div class="bottomnav">${ps.map(p=>`<button class="navitem ${p.id===current?'active':''}" onclick="go('${p.id}')"><span class="ico">${icon(p.id)}</span><span>${esc(short(p.title))}</span></button>`).join('')}</div>`}
function shell(body,title,ey='ILIAS COACH'){return `<div class="app">${top(title,ey)}<main class="screen">${body}</main>${bottom()}${editTools()}${drawerHtml()}</div>`}
function drawerHtml(){if(!drawer)return '';return `<div class="drawerback" onclick="toggleDrawer()"></div><aside class="drawer"><div class="brand"><div class="logo">IC</div><div><h2>ILIAS COACH</h2><p>TRAIN SMARTER · RECOVER STRONGER</p></div></div><div class="draweritems">${visiblePages().filter(p=>p.drawer).map(p=>`<button class="draweritem ${p.id===current?'active':''}" onclick="go('${p.id}')">${icon(p.id)} &nbsp; ${esc(p.title)}</button>`).join('')}</div></aside>`}
function editTools(){if(!state.features.editFab)return '';return `<div class="editbar"><button class="editfab" onclick="toggleEdit()">${editMode?'✓ Editing':'✎ Edit'}</button>${editMode?'<button class="editfab" onclick="go(\'owner\')">Owner</button>':''}</div>`}
window.toggleDrawer=()=>{drawer=!drawer;render()};window.toggleEdit=()=>{editMode=!editMode;render()};window.renameCurrent=()=>{const p=pageCfg(current);if(!p)return;const v=prompt('Page name',p.title);if(v&&v.trim()){p.title=v.trim();save();render()}};
function render(){const root=document.getElementById('app');if(player){root.innerHTML=playerHtml(player);bindPlayer();return}const p=pageCfg(current)||pageCfg('today');if(!p||!p.visible)current='today';const fn=pages[current]||customPage;root.innerHTML=fn()}
const pages={cover:cover,today:today,todayPlan:null,'today-plan':todayPlan,next:nextPage,programs:programs,recovery:recovery,nutrition:nutrition,progress:progress,music:music,owner:owner,settings:settings};
function cover(){return `<div class="app cover"><div class="coverpanel"><div class="covermark">IC</div><div class="eyebrow">PERSONAL ADAPTIVE COACH</div><h1>ILIAS<br>COACH</h1><div class="slogan">TRAIN SMARTER. RECOVER STRONGER.</div><p class="quiet">Training, physiotherapy, recovery and nutrition in one precise flow. Built around your focus, your capacity and your progress.</p><button class="cta" onclick="go('today')">START TODAY →</button></div>${drawerHtml()}</div>`}
function exerciseCard(id,sub='Tap for true Anatomy Motion'){const e=EX[id];return `<div class="card row" onclick="openExercise('${id}')"><img class="thumb" src="${e.img}"><div class="grow"><h3>${e.name}</h3><div class="meta">${e.cat}</div><div class="meta">${sub}</div></div><div>›</div></div>`}
function today(){return shell(`<div class="eyebrow">TODAY · ADAPTIVE PLAN</div><div class="hero"><img src="${EX['machine-chest-press'].img}"><div class="herobody"><div class="chips"><span class="chip">Upper ${state.focus.upper}%</span><span class="chip">Lower ${state.focus.lower}%</span><span class="chip">Pain-safe ${state.features.painSafe?'ON':'OFF'}</span></div><h2>Upper Body Strength</h2><p class="sub">5 exercises · 48 min · strength focus. Every exercise opens a dedicated motion player.</p><button class="cta" onclick="openExercise('machine-chest-press')">START WORKOUT →</button></div></div><div class="sectiontitle">Today's sequence</div>${exerciseCard('machine-chest-press')}${exerciseCard('face-pull')}${exerciseCard('supported-single-arm-dumbbell-row')}${exerciseCard('incline-dumbbell-press')}${exerciseCard('dumbbell-lateral-raise')}`,'Today','TRAIN · PHYSIO · NUTRITION · RECOVERY')}
function todayPlan(){const ids=['machine-chest-press','face-pull','supported-single-arm-dumbbell-row','incline-dumbbell-press','dumbbell-lateral-raise'];return shell(`<div class="sectiontitle">Ordered session</div>${ids.map((id,i)=>{const e=EX[id];return `<div class="card row" onclick="openExercise('${id}')"><div class="logo">${i+1}</div><img class="thumb" src="${e.img}"><div class="grow"><h3>${e.name}</h3><div class="meta">${e.sets} sets · ${e.reps} reps · ${e.rest} rest</div></div><div>›</div></div>`}).join('')}<button class="cta" onclick="go('owner')">EDIT PLAN STRUCTURE</button>`,'Today Plan','CURRENT WORKOUT')}
function nextPage(){return shell(`<div class="chips"><span class="chip">Upcoming</span><span class="chip">Calendar</span></div><div class="hero"><img src="${EX['goblet-squat'].img}"><div class="herobody"><div class="eyebrow">NEXT WORKOUT</div><h2>Lower Body Strength</h2><p class="sub">Tomorrow · 07:00–08:00. The plan adapts to Owner Controls.</p><button class="cta" onclick="openExercise('barbell-hip-thrust')">PREVIEW MOTION →</button></div></div><div class="sectiontitle">Upcoming sessions</div>${exerciseCard('barbell-hip-thrust','Lower body · verified motion video')}${exerciseCard('leg-press','Lower body · motion pending verification')}${exerciseCard('backward-sled-drag','Knee capacity · motion pending verification')}`,'Next','UPCOMING TRAINING')}
function programs(){const arr=[['Upper Body Strength','machine-chest-press'],['Lower Body Strength','barbell-hip-thrust'],['Knee Capacity','backward-sled-drag'],['Recovery & Rebuild','leg-press'],['Running Support','standing-calf-raise']];return shell(`<div class="sectiontitle">Adaptive programs</div>${arr.map(([n,id])=>`<div class="card row" onclick="openExercise('${id}')"><img class="thumb" src="${EX[id].img}"><div class="grow"><h3>${n}</h3><div class="meta">6–12 weeks · adjustable focus</div></div><div>›</div></div>`).join('')}`,'Programs','STRUCTURED TRAINING')}
function recovery(){return shell(`<div class="chips"><span class="chip">Knee</span><span class="chip">Hip</span><span class="chip">Back</span><span class="chip">Ankle</span></div><div class="metricgrid"><div class="metric"><strong>62</strong><span>RECOVERY</span></div><div class="metric"><strong>${state.focus.mobility}%</strong><span>MOBILITY</span></div><div class="metric"><strong>${state.features.painSafe?'ON':'OFF'}</strong><span>PAIN-SAFE</span></div></div><div class="sectiontitle">Capacity work</div>${exerciseCard('backward-sled-drag')}${exerciseCard('leg-press')}${exerciseCard('standing-calf-raise')}`,'Recovery / Physio','CAPACITY · MOBILITY · CONTROL')}
function nutrition(){return shell(`<div class="metricgrid"><div class="metric"><strong>2,400</strong><span>KCAL</span></div><div class="metric"><strong>160g</strong><span>PROTEIN</span></div><div class="metric"><strong>2.5L</strong><span>WATER</span></div></div><div class="sectiontitle">Today</div>${['Breakfast · oats + protein','Lunch · chicken + rice + vegetables','Dinner · salmon + potatoes + salad','Snack · yogurt / fruit / nuts'].map(x=>`<div class="card"><h3>${x}</h3><div class="meta">Tap in Owner Controls to replace or hide nutrition modules.</div></div>`).join('')}`,'Nutrition','FUEL · RECOVER · PERFORM')}
function progress(){return shell(`<div class="metricgrid"><div class="metric"><strong>+24%</strong><span>STRENGTH</span></div><div class="metric"><strong>4/5</strong><span>DAYS</span></div><div class="metric"><strong>85%</strong><span>RECOVERY</span></div></div><div class="sectiontitle">Strength trend</div><div class="chart"><svg viewBox="0 0 100 40" preserveAspectRatio="none"><polyline points="0,34 12,31 25,33 38,24 50,26 63,17 75,20 88,9 100,6" fill="none" stroke="#31b4ff" stroke-width="2"/></svg></div><div class="sectiontitle">Current focus</div><div class="card"><div class="sliderrow"><label>Upper body <b>${state.focus.upper}%</b></label><input type="range" min="0" max="100" value="${state.focus.upper}" disabled></div><div class="sliderrow"><label>Lower body <b>${state.focus.lower}%</b></label><input type="range" min="0" max="100" value="${state.focus.lower}" disabled></div></div>`,'Progress','MEASURE · ADAPT · IMPROVE')}
function music(){const connected=!!state.spotify.token;return shell(`<div class="hero"><div class="herobody"><div class="eyebrow">SPOTIFY</div><h2>${connected?'Connected':'Connect your music'}</h2><p class="sub">Motivational defaults: Eminem, Five Finger Death Punch, Armin van Buuren, Rocky-style training energy, cinematic focus and recovery.</p>${connected?'<button class="cta" onclick="spotifyDisconnect()">DISCONNECT</button>':'<button class="cta" onclick="spotifyConnect()">CONNECT SPOTIFY</button>'}</div></div><div class="sectiontitle">Training modes</div>${['Drive · Rap / Rock','Cardio · Trance / EDM','Focus · Cinematic','Recovery · Low energy'].map(x=>`<div class="card row"><div class="logo">♪</div><div class="grow"><h3>${x}</h3><div class="meta">Workout-linked playback mode</div></div><button class="smallbtn">▶</button></div>`).join('')}`,'Spotify / Music','MUSIC · DRIVE · FOCUS')}
function owner(){const ps=[...state.pages].sort((a,b)=>a.order-b.order);return shell(`<div class="notice">OWNER MODE is the actual app editor. Changes save on-device immediately. Hide, rename and reorder pages; choose bottom navigation and drawer membership; activate/deactivate features and map verified motion videos.</div><div class="sectiontitle">Page editor</div>${ps.map((p,i)=>`<div class="owneritem"><div><input type="text" value="${escAttr(p.title)}" onchange="renamePage('${p.id}',this.value)"><div class="chips"><label class="chip"><input type="checkbox" ${p.visible?'checked':''} onchange="pageFlag('${p.id}','visible',this.checked)"> visible</label><label class="chip"><input type="checkbox" ${p.bottom?'checked':''} onchange="pageFlag('${p.id}','bottom',this.checked)"> bottom</label><label class="chip"><input type="checkbox" ${p.drawer?'checked':''} onchange="pageFlag('${p.id}','drawer',this.checked)"> drawer</label></div></div><div><button class="smallbtn" onclick="movePage('${p.id}',-1)">↑</button> <button class="smallbtn" onclick="movePage('${p.id}',1)">↓</button><br><button class="smallbtn danger" onclick="archivePage('${p.id}')">Remove</button></div></div>`).join('')}<button class="cta" onclick="addPage()">+ ADD PAGE</button><div class="sectiontitle">Training focus</div>${slider('upper','Upper body')}${slider('lower','Lower body')}${slider('recovery','Recovery')}${slider('mobility','Mobility')}${slider('cardio','Cardio')}${slider('core','Core')}${slider('strength','Strength vs conditioning')}<div class="sectiontitle">Feature activation</div><div class="card">${Object.keys(state.features).map(k=>toggle(k,pretty(k))).join('')}</div><div class="sectiontitle">Motion library</div><div class="notice">Only verified true-motion MP4 files are used. Static illustrations are never animated artificially. Add a GitHub asset path or HTTPS MP4 below to override an exercise.</div>${Object.entries(EX).map(([id,e])=>`<div class="card"><div class="row"><img class="thumb" src="${e.img}"><div class="grow"><h3>${e.name}</h3><div class="meta">${motionUrl(id)?'✓ motion mapped':'Motion not installed'}</div></div></div><input type="text" style="width:100%;margin-top:12px;background:#050b0f;border:1px solid #24404e;border-radius:12px;color:#fff;padding:12px" placeholder="media/motion/file.mp4 or https://…" value="${escAttr(state.motion[id]||'')}" onchange="setMotion('${id}',this.value)"></div>`).join('')}<div class="sectiontitle">Spotify developer connection</div><div class="card"><label class="meta">Spotify Client ID</label><input type="text" style="width:100%;margin-top:8px;background:#050b0f;border:1px solid #24404e;border-radius:12px;color:#fff;padding:12px" value="${escAttr(state.spotify.clientId||'')}" onchange="setSpotifyClient(this.value)" placeholder="Public Client ID"><div class="meta" style="margin-top:8px">Redirect URI: iliascoach://spotify-callback</div></div>`,'Owner Controls','FULL APP EDITOR')}
function settings(){return shell(`<div class="card"><div class="toggleline"><div><b>Owner edit button</b><div class="meta">Show edit control on every screen</div></div>${switchHtml('editFab',state.features.editFab)}</div><div class="toggleline"><div><b>Anatomy Motion</b><div class="meta">True MP4 only</div></div>${switchHtml('anatomyMotion',state.features.anatomyMotion)}</div><div class="toggleline"><div><b>Pain-safe mode</b><div class="meta">Use symptom-aware options</div></div>${switchHtml('painSafe',state.features.painSafe)}</div></div><button class="smallbtn danger" onclick="resetApp()">RESET OWNER CONFIGURATION</button>`,'Settings','APP PREFERENCES')}
function customPage(){const p=pageCfg(current);return shell(`<div class="notice">Custom page. Use Owner Controls to rename, reorder, hide or remove it.</div><div class="card custommodule"><h3>${esc(p?.title||'Custom Page')}</h3><p class="meta">Custom modules can be added here in the next content pass.</p></div>`,p?.title||'Custom Page','CUSTOM MODULE')}
function slider(k,label){return `<div class="card sliderrow"><label>${label}<b>${state.focus[k]}%</b></label><input type="range" min="0" max="100" value="${state.focus[k]}" oninput="focusSet('${k}',this.value)"></div>`}
function toggle(k,label){return `<div class="toggleline"><div><b>${label}</b></div>${switchHtml(k,state.features[k])}</div>`}function switchHtml(k,on){return `<button class="switch ${on?'on':''}" onclick="featureSet('${k}',${!on})"></button>`}
window.focusSet=(k,v)=>{state.focus[k]=+v;if(k==='upper'){state.focus.lower=100-+v}else if(k==='lower'){state.focus.upper=100-+v}save();render()};window.featureSet=(k,v)=>{state.features[k]=v;save();render()};
window.renamePage=(id,v)=>{const p=pageCfg(id);if(p&&v.trim()){p.title=v.trim();save();render()}};window.pageFlag=(id,k,v)=>{const p=pageCfg(id);if(p){p[k]=v;save();render()}};window.movePage=(id,d)=>{const ps=state.pages.sort((a,b)=>a.order-b.order),i=ps.findIndex(p=>p.id===id),j=i+d;if(i<0||j<0||j>=ps.length)return;[ps[i].order,ps[j].order]=[ps[j].order,ps[i].order];save();render()};window.archivePage=id=>{if(id==='owner'){alert('Owner Controls cannot be removed; hide it from navigation instead.');return}const p=pageCfg(id);if(confirm('Remove '+p.title+' from the app?')){p.visible=false;p.bottom=false;p.drawer=false;save();if(current===id)current='owner';render()}};window.addPage=()=>{const title=prompt('New page name','New Page');if(!title)return;const id='custom-'+Date.now();state.pages.push({id,title:title.trim(),visible:true,drawer:true,bottom:false,order:Math.max(...state.pages.map(p=>p.order))+1,custom:true,modules:[]});save();render()};
window.setMotion=(id,v)=>{state.motion[id]=v.trim();save();render()};function motionUrl(id){return state.motion[id]||EX[id]?.video||''}
window.setSpotifyClient=v=>{state.spotify.clientId=v.trim();save()};window.spotifyDisconnect=()=>{delete state.spotify.token;save();render()};
window.spotifyConnect=async()=>{const client=state.spotify.clientId;if(!client){alert('Enter your Spotify Client ID in Owner Controls first.');go('owner');return}const verifier=randomString(64);localStorage.setItem('sp_verifier',verifier);const challenge=await sha256b64(verifier);const redirect='iliascoach://spotify-callback';const scope='user-read-playback-state user-modify-playback-state user-read-currently-playing';location.href='https://accounts.spotify.com/authorize?response_type=code&client_id='+encodeURIComponent(client)+'&scope='+encodeURIComponent(scope)+'&redirect_uri='+encodeURIComponent(redirect)+'&code_challenge_method=S256&code_challenge='+challenge};
window.spotifyCallback=async uri=>{try{const u=new URL(uri);const code=u.searchParams.get('code');if(!code)return;const verifier=localStorage.getItem('sp_verifier');const body=new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:'iliascoach://spotify-callback',client_id:state.spotify.clientId,code_verifier:verifier});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await r.json();if(j.access_token){state.spotify.token=j.access_token;save();current='music';render()}}catch(e){alert('Spotify callback failed')}};
function randomString(n){const a='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';let s='';const x=new Uint8Array(n);crypto.getRandomValues(x);for(const v of x)s+=a[v%a.length];return s}async function sha256b64(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
window.openExercise=id=>{player=id;drawer=false;tab='animation';render()};window.playerTab=t=>{tab=t;render()};
function playerHtml(id){const e=EX[id];const url=motionUrl(id);const has=!!url&&state.features.anatomyMotion;return `<div class="player"><div class="playertop"><button class="iconbtn" onclick="closePlayer()">←</button><div class="center"><div class="eyebrow">${esc(e.cat)}</div><b>${esc(e.name)}</b></div><button class="iconbtn" onclick="go('owner')">⚙</button></div><div class="motionstage">${has?`<video id="motionVideo" src="${escAttr(url)}" poster="${e.img}" autoplay muted playsinline ${state.features.autoLoop?'loop':''}></video>`:`<img src="${e.img}"><div class="motionmissing"><b class="limeText">VERIFIED MOTION NOT INSTALLED</b><br>Static anatomy is shown without fake animation. Add a verified MP4 in Owner Controls → Motion Library.</div>`}${state.features.anatomyMotion?'<div class="motionpill">ANATOMY MOTION ▶</div>':''}${state.features.formLock?'<div class="formpill">FORM LOCK 🔒</div>':''}${has?'<div class="videocontrols"><button class="round" id="speedBtn" onclick="cycleSpeed()">1×</button><button class="round play" id="playBtn" onclick="togglePlay()">Ⅱ</button></div>':''}</div><div class="playerbody"><div class="playertabs"><button class="${tab==='animation'?'active':''}" onclick="playerTab('animation')">Animation</button><button class="${tab==='muscles'?'active':''}" onclick="playerTab('muscles')">Muscles</button><button class="${tab==='instructions'?'active':''}" onclick="playerTab('instructions')">Instructions</button></div>${tabContent(e,has)}<div class="metricgrid"><div class="metric"><strong>${e.sets}</strong><span>SETS</span></div><div class="metric"><strong>${e.reps}</strong><span>REPS</span></div><div class="metric"><strong>${e.rest}</strong><span>REST</span></div></div><div class="card" style="margin-top:16px"><div class="eyebrow limeText">WORKOUT MODE</div><h3>Music ready · Spotify</h3><div class="meta">Playback can auto-start when Spotify is connected.</div></div></div></div>`}
function tabContent(e,has){if(tab==='muscles')return `<div class="notice"><b>${esc(e.cat)}</b><br>Primary muscle emphasis is highlighted in the verified exercise artwork.</div>`;if(tab==='instructions')return `<div class="notice"><b>FORM CUE</b><br>${esc(e.cue)}${state.features.painSafe?'<br><br>Pain-safe mode is active: stop or modify if symptoms meaningfully increase.':''}</div>`;return `<div class="eyebrow limeText" style="margin-top:20px">${esc(e.cat)}</div><h2>${esc(e.name)}</h2>${state.features.coachingText?`<p class="sub">${esc(e.cue)}</p>`:''}${has?'<div class="notice">True 24-fps MP4 motion playback. Tap pause to inspect any position; use speed control for technique review.</div>':''}`}
window.closePlayer=()=>{player=null;render()};window.togglePlay=()=>{const v=document.getElementById('motionVideo');if(!v)return;if(v.paused)v.play();else v.pause();document.getElementById('playBtn').textContent=v.paused?'▶':'Ⅱ'};let speedIndex=2;const speeds=[.5,.75,1,1.25,1.5];window.cycleSpeed=()=>{const v=document.getElementById('motionVideo');if(!v)return;speedIndex=(speedIndex+1)%speeds.length;v.playbackRate=speeds[speedIndex];document.getElementById('speedBtn').textContent=speeds[speedIndex]+'×'};function bindPlayer(){const v=document.getElementById('motionVideo');if(v){v.playbackRate=speeds[speedIndex];v.addEventListener('click',togglePlay)}}
window.resetApp=()=>{if(confirm('Reset all Owner Controls and page customisation?')){localStorage.removeItem('icv3');state=load();current='today';render()}};
function icon(id){return {cover:'⌂',today:'▣','today-plan':'☷',next:'→',programs:'▥',recovery:'◔',nutrition:'◉',progress:'▥',music:'♫',owner:'⚙',settings:'⚙'}[id]||'◆'}function short(s){return s.replace('Recovery / Physio','Recovery').replace('Spotify / Music','Music').replace('Owner Controls','Owner').slice(0,12)}function pretty(s){return s.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escAttr(s){return esc(s)}
if(!location.hash)history.replaceState({p:'today'},'','#today');else{const id=location.hash.slice(1);if(pageCfg(id))current=id}render();})();