plugins {
    id 'com.android.application'
}

android {
    namespace 'eu.shishalove.customer'
    compileSdk 35

    defaultConfig {
        applicationId 'eu.shishalove.customer'
        minSdk 24
        targetSdk 35
        versionCode 110
        versionName '1.1.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.dev'
            versionNameSuffix '-dev'
        }
        release {
            minifyEnabled false
        }
    }
}