from pathlib import Path
import re

A=Path('buildsrc/NAR-Mix/app/src/main/assets')
js=A/'app.js'; css=A/'app.css'
s=js.read_text()

# 1) Owner Studio gets a direct flavor editor entry.
s=s.replace(
'''<button id="adminLines"><b>Manage brands & lines</b><span>Add, rename, hide or restore line categories</span></button><button id="adminLayout">''',
'''<button id="adminLines"><b>Manage brands & lines</b><span>Add, rename, hide or restore line categories</span></button><button id="adminFlavors"><b>Manage flavors</b><span>Change brand, tobacco line, cover image, gallery and flavor details</span></button><button id="adminLayout">''',1)
s=s.replace(
"$('#adminLines').onclick=adminLinesModal;$('#adminLayout').onclick=adminLayoutModal;",
"$('#adminLines').onclick=adminLinesModal;$('#adminFlavors').onclick=adminFlavorsModal;$('#adminLayout').onclick=adminLayoutModal;",1)

# 2) Add searchable owner flavor list.
anchor='function adminLineBrandModal(brandId)'
pos=s.find(anchor)
if pos<0: raise SystemExit('admin line hook missing')
flavor_list_code=r'''
function adminFlavorsModal(){modal(`<div class="sheethead"><button id="adminFlavorsBack" class="backbtn">← Admin</button><span>Manage flavors</span></div><div class="adminFlavorSearch"><input id="adminFlavorQ" placeholder="Search flavor, brand or line…"><span>${DB.flavors.length} catalog flavors</span></div><div id="adminFlavorResults" class="adminFlavorResults"></div>`);$('#adminFlavorsBack').onclick=adminHomeModal;const renderList=()=>{const q=$('#adminFlavorQ').value.trim().toLowerCase();const rows=DB.flavors.filter(f=>{const b=brand(f.brand);return !q||[f.name,b?.name||'',f.line||'',...(f.notes||[])].join(' ').toLowerCase().includes(q)}).slice(0,120);$('#adminFlavorResults').innerHTML=rows.map(f=>`<button data-admin-flavor="${f.id}">${customPhotos(f)[0]?`<img src="${customPhotos(f)[0]}" alt="">`:`<span class="adminFlavorNoPhoto">${esc((f.name||'?').slice(0,1))}</span>`}<span><b>${esc(f.name)}</b><small>${esc(brand(f.brand)?.name||f.brand)} · ${esc(lineAlias(f.brand,f.line)||f.line||'—')}</small></span><i>EDIT ›</i></button>`).join('')||'<div class="empty">No matching flavors.</div>';$$('[data-admin-flavor]').forEach(x=>x.onclick=()=>adminFlavorModal(x.dataset.adminFlavor))};$('#adminFlavorQ').oninput=renderList;renderList()}
'''
s=s[:pos]+flavor_list_code+s[pos:]

# 3) Replace the old flavor editor with full brand/line/image control.
start=s.find('function adminFlavorModal(id)')
end=s.find('function adminBowlsModal()', start)
if start<0 or end<0: raise SystemExit('adminFlavorModal range missing')
new_editor=r'''function adminFlavorModal(id){const f=flavor(id);if(!f)return;const photos=customPhotos(f);const brands=DB.brands.slice();const currentBrand=brands.some(b=>b.id===f.brand)?f.brand:(brands[0]?.id||'');const lineOptions=rawLineNamesForBrand(brand(currentBrand));modal(`<div class="sheethead"><button id="adminFlavorBack" class="backbtn">← Flavors</button><span>Edit flavor</span></div><div class="adminFlavorIdentity"><div class="ownerCoverPreview">${photos[0]?`<img src="${photos[0]}" alt="${esc(f.name)}">`:`<div>${esc((f.name||'?').slice(0,1))}</div>`}<small>MAIN COVER</small></div><div><div class="eyebrow">OWNER OVERRIDE</div><h2>${esc(f.name)}</h2><p>${esc(brand(f.brand)?.name||f.brand)} · ${esc(lineAlias(f.brand,f.line)||f.line||'')}</p></div></div><div class="adminEdit"><label>Flavor name<input id="afName" value="${esc(f.name)}"></label><label>Brand<select id="afBrand">${brands.map(b=>`<option value="${b.id}" ${b.id===currentBrand?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label><label>Tobacco line<select id="afLineSelect"></select></label><label>Custom / new line<input id="afLineCustom" value="" placeholder="Leave empty to use selected line"></label><label>Ingredients / notes (one per line)<textarea id="afNotes">${esc((f.notes||[]).join('\n'))}</textarea></label><label>Official direction<textarea id="afOfficial">${esc(f.official||'')}</textarea></label><label>NĀR verdict<textarea id="afVerdict">${esc(f.verdict||'')}</textarea></label><label>Strength<input id="afStrength" value="${esc(f.strength||'')}"></label><div class="adminPhotoManager"><div class="adminPhotoHead"><b>Flavor images</b><span>${photos.length}/6</span></div>${photos.length?`<div class="adminPhotoGrid ownerPhotoGrid">${photos.map((src,i)=>`<div class="ownerPhotoTile ${i===0?'coverPhoto':''}"><img src="${src}" alt=""><span>${i===0?'MAIN COVER':'GALLERY '+(i+1)}</span>${i>0?`<button class="coverPick" data-cover-photo="${i}">SET COVER</button>`:''}<button class="removePick" data-remove-photo="${i}">REMOVE</button></div>`).join('')}</div>`:'<p>No owner photos yet. The catalog artwork remains until you add your own image.</p>'}<label class="photoPick strongPhotoPick">Replace main cover<input id="afCover" type="file" accept="image/*"><span>Choose one image from Gallery</span></label><label class="photoPick">Take cover photo<input id="afCamera" type="file" accept="image/*" capture="environment"><span>Open camera</span></label><label class="photoPick">Add gallery photos<input id="afPhoto" type="file" accept="image/*" multiple><span>Select up to ${Math.max(0,6-photos.length)} additional photos</span></label></div></div><button class="primary wide" id="afSave">SAVE FLAVOR CHANGES</button><button class="secondary wide" id="afRestore">RESTORE CATALOG VALUES</button>${id.startsWith('custom-')?'<button class="danger wide" id="afDelete">Delete custom flavor</button>':''}`);
 const fillLines=()=>{const bid=$('#afBrand').value,b=brand(bid),all=rawLineNamesForBrand(b),current=(bid===f.brand?f.line:'');$('#afLineSelect').innerHTML=(all.length?all:['Main']).map(line=>`<option value="${esc(line)}" ${line===current?'selected':''}>${esc(lineAlias(bid,line)||line)}</option>`).join('')};fillLines();$('#afBrand').onchange=fillLines;$('#adminFlavorBack').onclick=adminFlavorsModal;
 $$('[data-cover-photo]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.coverPhoto),next=photos.slice();const [picked]=next.splice(i,1);next.unshift(picked);f.adminPhotos=next;state.admin.flavors[id]=Object.assign({},state.admin.flavors[id]||{},{adminPhotos:next,adminPhoto:''});save();adminFlavorModal(id);toast('Main cover changed')});
 $$('[data-remove-photo]').forEach(b=>b.onclick=()=>{const next=photos.filter((_,i)=>i!==Number(b.dataset.removePhoto));f.adminPhotos=next;state.admin.flavors[id]=Object.assign({},state.admin.flavors[id]||{},{adminPhotos:next,adminPhoto:''});save();adminFlavorModal(id)});
 $('#afSave').onclick=async()=>{const bid=$('#afBrand').value;let line=$('#afLineCustom').value.trim()||$('#afLineSelect').value.trim()||'Main';const o={name:$('#afName').value.trim()||f.name,brand:bid,line,notes:$('#afNotes').value.split('\n').map(x=>x.trim()).filter(Boolean),official:$('#afOfficial').value.trim(),verdict:$('#afVerdict').value.trim(),strength:$('#afStrength').value.trim(),adminPhotos:photos.slice(),adminPhoto:''};const coverFile=$('#afCover').files?.[0]||$('#afCamera').files?.[0];if(coverFile){try{const cover=await readAdminImage(coverFile);if(o.adminPhotos.length)o.adminPhotos[0]=cover;else o.adminPhotos=[cover]}catch(e){toast('Main image could not be saved')}}const files=[...($('#afPhoto').files||[])].slice(0,Math.max(0,6-o.adminPhotos.length));for(const file of files){try{o.adminPhotos.push(await readAdminImage(file))}catch(e){toast('One gallery image could not be saved')}}Object.assign(f,o);state.admin.flavors[id]=Object.assign({},state.admin.flavors[id]||{},o);state.admin.extraLines[bid]=Array.isArray(state.admin.extraLines[bid])?state.admin.extraLines[bid]:[];if(!rawLineNamesForBrand(brand(bid)).includes(line))state.admin.extraLines[bid].push(line);const ci=state.admin.customFlavors.findIndex(x=>x.id===id);if(ci>=0)state.admin.customFlavors[ci]=Object.assign({},state.admin.customFlavors[ci],o);save();closeModal();detail(id);toast('Flavor, line and images updated')};
 $('#afRestore').onclick=()=>{if(!confirm('Restore this flavor to the original catalog values and remove owner photos?'))return;delete state.admin.flavors[id];if(!id.startsWith('custom-')){toast('Catalog values will be restored after reopening NĀR');save();closeModal();location.reload()}else{toast('Custom flavors do not have catalog values')}};
 if($('#afDelete'))$('#afDelete').onclick=()=>{state.admin.customFlavors=state.admin.customFlavors.filter(x=>x.id!==id);delete state.admin.flavors[id];const ix=DB.flavors.findIndex(x=>x.id===id);if(ix>=0)DB.flavors.splice(ix,1);state.owned=state.owned.filter(x=>x!==id);state.wish=state.wish.filter(x=>x!==id);save();closeModal();tab='search';app();toast('Custom flavor deleted')}
}
'''
s=s[:start]+new_editor+s[end:]

js.write_text(s)

c=css.read_text()
c += r'''

/* ===== NAR MIX 4.6 — FULL OWNER FLAVOR EDITOR ===== */
.adminFlavorSearch{display:grid;gap:10px;margin:12px 0 18px}.adminFlavorSearch input,.adminEdit select{width:100%;box-sizing:border-box;background:#0d0c09;color:#f5eee3;border:1px solid rgba(199,142,78,.35);border-radius:14px;padding:13px 14px;font:inherit}.adminFlavorSearch span{font-size:11px;color:#92897e}.adminFlavorResults{display:grid;gap:9px}.adminFlavorResults>button{display:grid;grid-template-columns:54px 1fr auto;gap:12px;align-items:center;width:100%;text-align:left;padding:10px;border-radius:16px;background:#100e0b;border:1px solid rgba(190,132,73,.25);color:#f5eee3}.adminFlavorResults img,.adminFlavorNoPhoto{width:54px;height:54px;border-radius:12px;object-fit:cover;background:#23170f;display:grid;place-items:center;color:#efbd78;font:700 20px Georgia,serif}.adminFlavorResults span{display:grid;gap:4px}.adminFlavorResults small{color:#988f84}.adminFlavorResults i{font-style:normal;color:#e5b36f;font-size:11px}.adminFlavorIdentity{display:grid;grid-template-columns:92px 1fr;gap:16px;align-items:center;margin:12px 0 18px}.ownerCoverPreview{position:relative;width:92px;height:108px;border-radius:18px;overflow:hidden;background:#1a120b;border:1px solid rgba(213,153,85,.4)}.ownerCoverPreview img{width:100%;height:100%;object-fit:cover}.ownerCoverPreview>div{height:100%;display:grid;place-items:center;font:700 35px Georgia,serif;color:#efbd78}.ownerCoverPreview small{position:absolute;left:6px;bottom:6px;background:rgba(0,0,0,.75);padding:4px 6px;border-radius:7px;color:#f1c77b;font-size:7px;letter-spacing:.12em}.ownerPhotoGrid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.ownerPhotoTile{display:grid!important;grid-template-columns:1fr!important;gap:6px!important;padding:7px!important;background:#0c0b08!important;border:1px solid rgba(190,132,73,.25)!important;border-radius:14px!important}.ownerPhotoTile.coverPhoto{border-color:#e4ad5d!important;box-shadow:0 0 0 1px rgba(228,173,93,.18)}.ownerPhotoTile img{width:100%!important;height:120px!important;object-fit:cover!important;border-radius:10px!important}.ownerPhotoTile span{font-size:8px;color:#d6a45f;letter-spacing:.12em}.ownerPhotoTile button{position:static!important;width:100%!important;height:auto!important;border-radius:9px!important;padding:7px!important;font-size:9px!important}.coverPick{background:#d39a4e!important;color:#140d07!important}.removePick{background:#24120e!important;color:#ffb4a2!important}.strongPhotoPick{border-color:#d9a357!important;background:rgba(188,126,58,.08)!important}
'''
css.write_text(c)
print('Patched NAR Mix 4.6 full flavor owner editor: brand, line, cover, gallery, camera, restore')
